// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_PanelBtnBG;
extern lv_obj_t * ui_labelhourmin;
extern lv_obj_t * ui_Labelsec;
extern lv_obj_t * ui_Labelspo2;
extern lv_obj_t * ui_Labelheart;
extern lv_obj_t * ui_Labelmonth;
extern lv_obj_t * ui_Labelsta;
extern lv_obj_t * ui_labelcalories;
extern lv_obj_t * ui_wangcai;
extern lv_obj_t * ui_spo2;
extern lv_obj_t * ui_heart;
extern lv_obj_t * ui_calories;
extern lv_obj_t * ui_happy;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_PanelStatus;
extern void ui_event_light(lv_event_t * e);
extern lv_obj_t * ui_light;
extern lv_obj_t * ui_HandleBarTop;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_sun;
extern lv_obj_t * ui_PanelRight;
extern lv_obj_t * ui_HandleBarRight;
extern lv_obj_t * ui_PanelBottom;
extern lv_obj_t * ui_HandleBarBottom;
extern lv_obj_t * ui_PanelFunc;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

