// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_labelclock = NULL;
lv_obj_t * ui_Labelspo2 = NULL;
lv_obj_t * ui_Labelheart = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_PanelStatus = NULL;
lv_obj_t * ui_light = NULL;
lv_obj_t * ui_PanelFunc = NULL;
lv_obj_t * ui_Spinbox1 = NULL;
lv_obj_t * ui_PanelRight = NULL;
lv_obj_t * ui_PanelBottom = NULL;
// event funtions
void ui_event_light(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnBrightnessChange(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelclock = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelclock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelclock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelclock, -9);
    lv_obj_set_y(ui_labelclock, 2);
    lv_obj_set_align(ui_labelclock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelclock, "00:00");
    lv_obj_set_style_text_color(ui_labelclock, lv_color_hex(0xD82727), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_labelclock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelspo2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Labelspo2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelspo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelspo2, 68);
    lv_obj_set_y(ui_Labelspo2, 104);
    lv_obj_set_align(ui_Labelspo2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelspo2, "0");
    lv_obj_set_style_text_color(ui_Labelspo2, lv_color_hex(0xB51D1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelspo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelheart = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Labelheart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelheart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelheart, -54);
    lv_obj_set_y(ui_Labelheart, 102);
    lv_obj_set_align(ui_Labelheart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelheart, "0");
    lv_obj_set_style_text_color(ui_Labelheart, lv_color_hex(0xF01111), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelheart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 20);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 90);
    lv_obj_set_y(ui_Bar1, -80);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    ui_PanelStatus = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelStatus, 240);
    lv_obj_set_height(ui_PanelStatus, 280);
    lv_obj_set_x(ui_PanelStatus, 0);
    lv_obj_set_y(ui_PanelStatus, -280);
    lv_obj_clear_flag(ui_PanelStatus, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelStatus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelStatus, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PanelStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_light = lv_slider_create(ui_PanelStatus);
    lv_slider_set_range(ui_light, 50, 100);
    lv_slider_set_value(ui_light, 100, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_light) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_light, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_light, 150);
    lv_obj_set_height(ui_light, 20);
    lv_obj_set_x(ui_light, 0);
    lv_obj_set_y(ui_light, 10);
    lv_obj_set_align(ui_light, LV_ALIGN_CENTER);

    ui_PanelFunc = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelFunc, 240);
    lv_obj_set_height(ui_PanelFunc, 280);
    lv_obj_set_x(ui_PanelFunc, -240);
    lv_obj_set_y(ui_PanelFunc, 0);
    lv_obj_clear_flag(ui_PanelFunc, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelFunc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelFunc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelFunc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelFunc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelFunc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PanelFunc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinbox1 = lv_spinbox_create(ui_PanelFunc);
    lv_obj_set_width(ui_Spinbox1, 70);
    lv_obj_set_height(ui_Spinbox1, 42);
    lv_obj_set_x(ui_Spinbox1, -1);
    lv_obj_set_y(ui_Spinbox1, 68);
    lv_obj_set_align(ui_Spinbox1, LV_ALIGN_CENTER);
    lv_spinbox_set_digit_format(ui_Spinbox1, 4, 2);
    lv_spinbox_set_range(ui_Spinbox1, 0, 9999);
    lv_spinbox_set_cursor_pos(ui_Spinbox1, 1 - 1);

    ui_PanelRight = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelRight, 240);
    lv_obj_set_height(ui_PanelRight, 280);
    lv_obj_set_x(ui_PanelRight, 240);
    lv_obj_set_y(ui_PanelRight, 0);
    lv_obj_clear_flag(ui_PanelRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelRight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PanelRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelBottom = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelBottom, 240);
    lv_obj_set_height(ui_PanelBottom, 280);
    lv_obj_set_x(ui_PanelBottom, 0);
    lv_obj_set_y(ui_PanelBottom, 280);
    lv_obj_clear_flag(ui_PanelBottom, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PanelBottom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PanelBottom, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelBottom, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelBottom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelBottom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PanelBottom, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_light, ui_event_light, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_labelclock = NULL;
    ui_Labelspo2 = NULL;
    ui_Labelheart = NULL;
    ui_Bar1 = NULL;
    ui_PanelStatus = NULL;
    ui_light = NULL;
    ui_PanelFunc = NULL;
    ui_Spinbox1 = NULL;
    ui_PanelRight = NULL;
    ui_PanelBottom = NULL;

}
