// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Button02 = NULL;
lv_obj_t * ui_Labelheart = NULL;
lv_obj_t * ui_Labelspo2 = NULL;
lv_obj_t * ui_Switch4 = NULL;
// event funtions
void ui_event_Switch4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 20, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button02 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button02, 100);
    lv_obj_set_height(ui_Button02, 50);
    lv_obj_set_x(ui_Button02, 2);
    lv_obj_set_y(ui_Button02, 32);
    lv_obj_set_align(ui_Button02, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button02, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button02, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Labelheart = lv_label_create(ui_Button02);
    lv_obj_set_width(ui_Labelheart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelheart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelheart, 0);
    lv_obj_set_y(ui_Labelheart, 15);
    lv_obj_set_align(ui_Labelheart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelheart, "0");

    ui_Labelspo2 = lv_label_create(ui_Button02);
    lv_obj_set_width(ui_Labelspo2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelspo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelspo2, 0);
    lv_obj_set_y(ui_Labelspo2, -15);
    lv_obj_set_align(ui_Labelspo2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelspo2, "0");

    ui_Switch4 = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_Switch4, 75);
    lv_obj_set_height(ui_Switch4, 40);
    lv_obj_set_x(ui_Switch4, -6);
    lv_obj_set_y(ui_Switch4, -75);
    lv_obj_set_align(ui_Switch4, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_Switch4, ui_event_Switch4, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Button02 = NULL;
    ui_Labelheart = NULL;
    ui_Labelspo2 = NULL;
    ui_Switch4 = NULL;

}
