// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Button01;
extern lv_obj_t * ui_labelclock;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Labelspo2;
extern lv_obj_t * ui_Labelheart;
extern lv_obj_t * ui_PanelStatus;
extern lv_obj_t * ui_Bar1;
extern void ui_event_light(lv_event_t * e);
extern lv_obj_t * ui_light;
extern lv_obj_t * ui_PanelFunc;
extern lv_obj_t * ui_Spinbox1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

